from typing import Any

from TwitchChannelPointsMiner.platform.paths import ACCOUNTS_DIR, ensure_dirs

ACCOUNT_TEMPLATE = '''# -*- coding: utf-8 -*-
# Auto-generated by Twitch Points Miner dashboard. Do not edit headers manually.
import logging
from colorama import Fore

from TwitchChannelPointsMiner import TwitchChannelPointsMiner
from TwitchChannelPointsMiner.logger import LoggerSettings, ColorPalette
from TwitchChannelPointsMiner.classes.Chat import ChatPresence
from TwitchChannelPointsMiner.classes.Settings import Priority
from TwitchChannelPointsMiner.classes.entities.Bet import (
    Strategy,
    BetSettings,
    Condition,
    OutcomeKeys,
    FilterCondition,
    DelayMode,
)
from TwitchChannelPointsMiner.classes.entities.Streamer import StreamerSettings


def create_miner():
    priority = []
{priority_lines}

    return TwitchChannelPointsMiner(
        username="{username}",
        password={password},
        claim_drops_startup={claim_drops_startup},
        enable_analytics=True,
        disable_ssl_cert_verification=False,
        disable_at_in_nickname=False,
        priority=priority,
        logger_settings=LoggerSettings(
            save={save_logs},
            console_level=logging.INFO,
            console_username=True,
            auto_clear=True,
            time_zone="",
            file_level=logging.INFO,
            emoji=True,
            less={less_logs},
            colored=True,
            color_palette=ColorPalette(
                STREAMER_online="GREEN",
                streamer_offline="red",
                BET_wiN=Fore.MAGENTA,
            ),
        ),
        streamer_settings=StreamerSettings(
            make_predictions={make_predictions},
            follow_raid={follow_raid},
            claim_drops={claim_drops},
            claim_moments={claim_moments},
            watch_streak={watch_streak},
            community_goals=False,
            chat=ChatPresence.{chat_presence},
            bet=BetSettings(
                strategy=Strategy.{bet_strategy},
                percentage={bet_percentage},
                percentage_gap=20,
                max_points={bet_max_points},
                stealth_mode=True,
                delay_mode=DelayMode.FROM_END,
                delay=6,
                minimum_points=0,
                filter_condition=FilterCondition(
                    by=OutcomeKeys.TOTAL_USERS,
                    where=Condition.LTE,
                    value=800,
                ),
            ),
        ),
    )
'''


def _py_bool(v: Any) -> str:
    return "True" if bool(v) else "False"


def _py_int(v: Any, default: int) -> int:
    if v is None or v == "":
        return default
    try:
        return int(v)
    except (TypeError, ValueError):
        return default


def _py_str(v: Any) -> str:
    s = str(v).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def write_account_file(username: str, config: dict[str, Any]):
    ensure_dirs()
    priority_lines = []
    if config.get("priority_streak", True):
        priority_lines.append("    priority.append(Priority.STREAK)")
    if config.get("priority_drops", True):
        priority_lines.append("    priority.append(Priority.DROPS)")
    if config.get("priority_order", True):
        priority_lines.append("    priority.append(Priority.ORDER)")
    if not priority_lines:
        priority_lines.append("    priority.append(Priority.ORDER)")

    password = config.get("password")
    password_py = _py_str(password) if password else "None"

    content = ACCOUNT_TEMPLATE.format(
        username=username,
        password=password_py,
        priority_lines="\n".join(priority_lines),
        claim_drops_startup=_py_bool(config.get("claim_drops_startup", False)),
        save_logs=_py_bool(config.get("save_logs", True)),
        less_logs=_py_bool(config.get("less_logs", False)),
        make_predictions=_py_bool(config.get("make_predictions", True)),
        follow_raid=_py_bool(config.get("follow_raid", True)),
        claim_drops=_py_bool(config.get("claim_drops", True)),
        claim_moments=_py_bool(config.get("claim_moments", True)),
        watch_streak=_py_bool(config.get("watch_streak", True)),
        chat_presence=str(config.get("chat_presence", "ONLINE")).upper(),
        bet_strategy=str(config.get("bet_strategy") or "SMART").upper(),
        bet_percentage=_py_int(config.get("bet_percentage"), 5),
        bet_max_points=_py_int(config.get("bet_max_points"), 50000),
    )

    path = ACCOUNTS_DIR / f"{username}.py"
    path.write_text(content, encoding="utf-8")
